name: data_warehouse
version: '1.0'

profile: my-data-warehouse-profile

source-paths: 
  - models

target-path: target

clean-targets:
  - target

models:
  my_data_warehouse:
    schema: my_schema
  materialized: view

seeds:
  my_seed_data:
    enabled: true
    schema: my_schema
    quoting: true

snapshots:
  my_data_snapshots:
    schema: my_schema
    strategy: check