version: '3'
services:
  airflow:
    image: apache/airflow:latest
    ports:
      - 8080:8080
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////airflow/airflow.db
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs